### ISSUE TITLE
fontSize has no effect on `<Run>`

### ISSUE THREAD

**Issue by dstaley** [asklar/react-native-xaml#91]
```jsx
<TextBlock>
  <Run fontSize={48} text="Text should be large" />
</TextBlock>
```

The above renders the text in the default font size rather than the larger size specified by `fontSize`.

**Comment by asklar** [comment]
Good bug. RNW allows view managers to produce `FrameworkElement`. Run and other things are not FEs, so react-native-xaml fakes this by wrapping it in a ContentControl, and when it is asked to associate a child to its parent, it unwraps the non-FE child  and does its magic.
To determine how to set a property, we have a map of property names and a lambda that checks whether the entry is applicable to a certain object or not. This check basically does a cast to check if the object you pass in is of the type that the property is defined in.

`fontSize` is special in that the property is defined in several types:

```cpp
        { MAKE_KEY("fontSize"), AsType<winrt::Windows::UI::Xaml::Controls::ContentPresenter>,  []() { return winrt::Windows::UI::Xaml::Controls::ContentPresenter::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
        { MAKE_KEY("fontSize"), AsType<winrt::Windows::UI::Xaml::Controls::Control>,  []() { return winrt::Windows::UI::Xaml::Controls::Control::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
        { MAKE_KEY("fontSize"), AsType<winrt::Windows::UI::Xaml::Controls::FontIcon>,  []() { return winrt::Windows::UI::Xaml::Controls::FontIcon::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
        { MAKE_KEY("fontSize"), AsType<winrt::Windows::UI::Xaml::Controls::RichTextBlock>,  []() { return winrt::Windows::UI::Xaml::Controls::RichTextBlock::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
        { MAKE_KEY("fontSize"), AsType<winrt::Windows::UI::Xaml::Controls::TextBlock>,  []() { return winrt::Windows::UI::Xaml::Controls::TextBlock::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
        { MAKE_KEY("fontSize"), AsUnwrappedType<winrt::Windows::UI::Xaml::Documents::TextElement>,  []() { return winrt::Windows::UI::Xaml::Documents::TextElement::FontSizeProperty(); }, SetPropValue<double>, ViewManagerPropertyType::Number },
```

What is happening is that we come in with the Run's associated ContentControl wrapper, and we hit the second entry in the table that says "sure, I know how to set a Control's `fontSize`", and we stop looking.

I think the fix is to re-sort this table by property name first (as it is today), but then sort by specificity (the `TextElement` cast should come before the `Control` one)
